### ISSUE TITLE
Error processing job: ffprobe process exited with code 1.

### ISSUE THREAD

**Issue by alexnxt20** [fredrikburmester/streamyfin-optimized-versions-server#13]
Running optimized server on docker container using Portainer on a rpi-5.

Every time I queue a job it immediately fails and returns the following error: _"ERROR Error processing job bf404ce4-1c43-42c5-8d6b-c95e17a403fb: ffprobe process exited with code 1"_

**Comment by stephenwebb97** [comment]
I'm having the same issue, but on x64 unraid server.

**Comment by notian85** [comment]
Same issue here on unraid server.

**Comment by Kigstn** [comment]
Got the same issue (probaly). Ruinning on proxmox on an AMD cpu

### Logs
```py
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [NestFactory] Starting Nest application...
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +12ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [Bootstrap] Successfully connected to Jellyfin server: http://jellyfin:8096
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RoutesResolver] AppController {/}: +6ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/statistics, GET} route +3ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/optimize-version, POST} route +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/job-status/:id, GET} route +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/start-job/:id, POST} route +1ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/cancel-job/:id, DELETE} route +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/all-jobs, GET} route +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/download/:id, GET} route +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [RouterExplorer] Mapped {/delete-cache, DELETE} route +0ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [NestApplication] Nest application successfully started +11ms
[Nest] 1  - 06/16/2025, 9:43:36 PM     LOG [Bootstrap] Application is running on: http://[::1]:3000
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG Optimize request for URL: https://jellyfin.pi.djaekel.com/videos/bc7bdfa4-86...
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG Queueing job 0454eec7-c62b-4129-b177-60bc04567a97 | URL: http://jellyfin:8096/videos/bc7bdfa4-8665-375e-c6b... | Path: /usr/src/app/cache/combined_0454eec7-c62b-4129-b177-60bc04567a97.mp4
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG 0 active jobs running and 1 items in the queue
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG Optimizing - device 31d426e8-02da-4b53-8ab9-daf190825ff0 has 0 downloads waiting
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG Device ID 31d426e8-02da-4b53-8ab9-daf190825ff0 is not in the finished jobs. Optimizing not Allowed
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG 0 deviceIDs have recently finished a job
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG Started job 0454eec7-c62b-4129-b177-60bc04567a97
[Nest] 1  - 06/16/2025, 9:45:33 PM   ERROR Error processing job 0454eec7-c62b-4129-b177-60bc04567a97: ffprobe process exited with code 1
[Nest] 1  - 06/16/2025, 9:45:33 PM     LOG 0 active jobs running and 0 items in the queue
```

### Docker Compose File
```yaml
  streamyfin_optimised_server:
    image: 
      fredrikburmester/streamyfin-optimized-versions-server:master
    
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - JELLYFIN_URL=http://jellyfin:8096
      - MAX_CONCURRENT_JOBS=3

    devices:
      - /dev/dri:/dev/dri

    networks:
      - jellyfin
    
    ports:
      - 8211:3000

    restart: unless-stopped
```
