### ISSUE TITLE
Always returning 401 error

### ISSUE THREAD

**Issue by cy1der** [fredrikburmester/streamyfin-optimized-versions-server#14]
TLDR: Unless I'm missing something here, whatever I put in the authorization header, the request fails

---

I set up the optimize server using this docker compose:
```yaml
# ...
optimized:
    image: fredrikburmester/streamyfin-optimized-versions-server:master
    container_name: optimized
    hostname: optimized
    # ports:
      # - 3000:3000
    networks:
      default:
      npm:
        ipv4_address: 192.168.32.18
    environment:
      - NODE_ENV=production
      - JELLYFIN_URL=http://jellyfin:8096
      - MAX_CONCURRENT_JOBS=1
    volumes:
      - optimized_cache:/usr/src/app/cache
    restart: unless-stopped
# ...
```
Few notes:
- Commented out ports is intentional, I rely on internal docker networking for apps to access each other to minimize the number of open ports on my server
- Yes, optimized can access jellyfin: `Successfully connected to Jellyfin server: http://jellyfin:8096`
- Given the name of the npm network, I use Nginx Proxy Manager, config is below

![Image](https://github.com/user-attachments/assets/7e38d64a-d1c5-4327-a60d-db55095017f2)
![Image](https://github.com/user-attachments/assets/bcc9b8b8-9869-43ef-95e8-9aa529b843df)

After setting up Streamyfin and pointing it to the optimized server, downloading fails, and logs aren't that verbose:
![Image](https://github.com/user-attachments/assets/62ba81e4-4837-415b-a727-1ba5b8b03788)

Upon inspecting the code, I found the `authorization` header is needed to pass to jellyfin, so I tried curling the statistics endpoint to see if I get anything:
```bash
curl -X GET "https://jf-o.mydomain.tld/statistics" -H 'authorization: xyz' # literally 'xyz' here, I also tried putting a device token and api key too
{"message":"Authentication failed","error":"Unauthorized","statusCode":401}
```

Optimized logs, nothing special I assume:
```
UnauthorizedException: Invalid credentials
at AuthMiddleware.use (/usr/src/app/dist/auth.middleware.js:26:23)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
response: {
   message: 'Invalid credentials',
   error: 'Unauthorized',
   statusCode: 401
  },
  status: 401,
  options: {}
}
```

No matter what I put in the authorization header (as far as I've tried), the request ends up in that error, unless there is something that I did wrong.

<sub><sup>Sorry for the info dump lol, figured it helps for debugging</sup></sub>
