### ISSUE TITLE
Add GPU support

### ISSUE THREAD

**Issue by Darkatek7** [fredrikburmester/streamyfin-optimized-versions-server#17]
would be nice to also have gpu support for transcoding.

For most containers this is achieved via adding /dev/dri like this:
```
services:
  streamyfin-optimized-versions-server:
    image: fredrikburmester/streamyfin-optimized-versions-server:master
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: always
    # If you want to use a local volume for the cache, uncomment the following lines:
    volumes:
      - /srv/streamyfin-optimized-versions-server/cache:/usr/src/app/cache
    devices:
      - /dev/dri/:/dev/dri/
networks:
  default:
    name: nginxproxymanager_default
    external: true
```

For my Server specific it would be Intel GPU support.
